import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const isLucasAlreadyHome = ![2, 3, 4].includes(new Date().getDay());
  const answer = isLucasAlreadyHome ? "Nope, still at Sisy 🦆" : "Yes";
  return (
    <div className={styles.container}>
      <Head>
        <title>Is Lucas already at home?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Is Lucas already at home?</h1>
        <h2>{answer}</h2>
      </main>
    </div>
  );
}
